# Generated by Django 5.0.5 on 2024-05-07 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('stage', models.CharField(blank=True, null=True, choices=[('ТЗ', 'ТЗ'), ('Закупка', 'Закупка'), ('Проектирование', 'Проектирование'), ('Опытная эксплуатация', 'Опытная эксплуатация'), ('ПМИ', 'ПМИ'), ('Завершено', 'Завершено'), ('Внедрение', 'Внедрение')], max_length=20)),
                ('status', models.CharField(blank=True, null=True, choices=[('Открыто', 'Открыто'), ('Закрыто', 'Закрыто'), ('Ожидание', 'Ожидание')], max_length=20)),
                ('basis', models.TextField(blank=True, null=True)),
                ('representive', models.CharField(blank=True, null=True, choices=[('УМК', 'УМК'), ('Фонд ТиУ', 'Фонд ТиУ')], max_length=50)),
                ('foreigh_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('analytic', models.CharField(choices=[('Голубев А.А.', 'Голубев А.А.'), ('Пискарев С.Н.', 'Пискарев С.Н.'), ('Клюжин А.О.', 'Клюжин А.О.'), ('Асмаев А.А.', 'Асмаев А.А.')], max_length=50)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('modify_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('activity', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_activities', to='myapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('week_activities', models.ManyToManyField(blank=True, to='myapp.weekactivity')),
            ],
        ),
    ]
