# Generated by Django 5.0.5 on 2024-05-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240507_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='modify_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='representive',
            field=models.CharField(choices=[('УМК', 'УМК'), ('Фонд ТиУ', 'Фонд ТиУ')], default='Фонд ТиУ', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('ТЗ', 'ТЗ'), ('Закупка', 'Закупка'), ('Проектирование', 'Проектирование'), ('Опытная эксплуатация', 'Опытная эксплуатация'), ('ПМИ', 'ПМИ'), ('Завершено', 'Завершено'), ('Внедрение', 'Внедрение')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Открыто', 'Открыто'), ('Закрыто', 'Закрыто'), ('Ожидание', 'Ожидание')], max_length=20, null=True),
        ),
    ]
